//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Bosch jackhammer.
        /// </summary>
        public static string BoschJackhammerDescription {
            get {
                return ResourceManager.GetString("BoschJackhammerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosch jackhammer.
        /// </summary>
        public static string BoschJackhammerName {
            get {
                return ResourceManager.GetString("BoschJackhammerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Caterpillar bulldozer.
        /// </summary>
        public static string CaterpillarBulldozerDescription {
            get {
                return ResourceManager.GetString("CaterpillarBulldozerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caterpillar bulldozer.
        /// </summary>
        public static string CaterpillarBulldozerName {
            get {
                return ResourceManager.GetString("CaterpillarBulldozerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day(s).
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this item?.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Details.
        /// </summary>
        public static string DetailsObject {
            get {
                return ResourceManager.GetString("DetailsObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This equipment item added before..
        /// </summary>
        public static string DuplicateItem {
            get {
                return ResourceManager.GetString("DuplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Id.
        /// </summary>
        public static string EquipmentId {
            get {
                return ResourceManager.GetString("EquipmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipments Cart.
        /// </summary>
        public static string EquipmentsCart {
            get {
                return ResourceManager.GetString("EquipmentsCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipments List.
        /// </summary>
        public static string EquipmentsList {
            get {
                return ResourceManager.GetString("EquipmentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Invoice.
        /// </summary>
        public static string GenerateInvoice {
            get {
                return ResourceManager.GetString("GenerateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to generate invoice?.
        /// </summary>
        public static string GenerateInvoiceMessage {
            get {
                return ResourceManager.GetString("GenerateInvoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online construction equipment rental.
        /// </summary>
        public static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment item(s) :.
        /// </summary>
        public static string InvoiceEquipmentItems {
            get {
                return ResourceManager.GetString("InvoiceEquipmentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice for order contains {0} item(s), Invoice Date: {1}.
        /// </summary>
        public static string InvoiceHeader {
            get {
                return ResourceManager.GetString("InvoiceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item no. {0}: {1} with price: {2}{3}.
        /// </summary>
        public static string InvoiceItemNoAndPrice {
            get {
                return ResourceManager.GetString("InvoiceItemNoAndPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Gain: {0} Loyalty point(s).
        /// </summary>
        public static string InvoiceTotalLoyaltyPoints {
            get {
                return ResourceManager.GetString("InvoiceTotalLoyaltyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price of the invoice: {0}{1}.
        /// </summary>
        public static string InvoiceTotalPrice {
            get {
                return ResourceManager.GetString("InvoiceTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of KamAZ truck.
        /// </summary>
        public static string KamAZTruckDescription {
            get {
                return ResourceManager.GetString("KamAZTruckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KamAZ truck.
        /// </summary>
        public static string KamAZTruckName {
            get {
                return ResourceManager.GetString("KamAZTruckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Komatsu crane.
        /// </summary>
        public static string KomatsuCraneDescription {
            get {
                return ResourceManager.GetString("KomatsuCraneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komatsu crane.
        /// </summary>
        public static string KomatsuCraneName {
            get {
                return ResourceManager.GetString("KomatsuCraneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental days should be between 1 and 365..
        /// </summary>
        public static string RentalDaysWarning {
            get {
                return ResourceManager.GetString("RentalDaysWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental for.
        /// </summary>
        public static string RentalFor {
            get {
                return ResourceManager.GetString("RentalFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Days.
        /// </summary>
        public static string RentDays {
            get {
                return ResourceManager.GetString("RentDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary: .
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Volvo steamroller.
        /// </summary>
        public static string VolvoSteamrollerDescription {
            get {
                return ResourceManager.GetString("VolvoSteamrollerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volvo steamroller.
        /// </summary>
        public static string VolvoSteamrollerName {
            get {
                return ResourceManager.GetString("VolvoSteamrollerName", resourceCulture);
            }
        }
    }
}
